// Generated by gencpp from file lab03_example_srv/point_rotResponse.msg
// DO NOT EDIT!


#ifndef LAB03_EXAMPLE_SRV_MESSAGE_POINT_ROTRESPONSE_H
#define LAB03_EXAMPLE_SRV_MESSAGE_POINT_ROTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace lab03_example_srv
{
template <class ContainerAllocator>
struct point_rotResponse_
{
  typedef point_rotResponse_<ContainerAllocator> Type;

  point_rotResponse_()
    : out_p()  {
    }
  point_rotResponse_(const ContainerAllocator& _alloc)
    : out_p(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _out_p_type;
  _out_p_type out_p;





  typedef boost::shared_ptr< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct point_rotResponse_

typedef ::lab03_example_srv::point_rotResponse_<std::allocator<void> > point_rotResponse;

typedef boost::shared_ptr< ::lab03_example_srv::point_rotResponse > point_rotResponsePtr;
typedef boost::shared_ptr< ::lab03_example_srv::point_rotResponse const> point_rotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab03_example_srv::point_rotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab03_example_srv::point_rotResponse_<ContainerAllocator1> & lhs, const ::lab03_example_srv::point_rotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.out_p == rhs.out_p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab03_example_srv::point_rotResponse_<ContainerAllocator1> & lhs, const ::lab03_example_srv::point_rotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab03_example_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dacb06ab550d43eb948e7b712dd4d7c8";
  }

  static const char* value(const ::lab03_example_srv::point_rotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdacb06ab550d43ebULL;
  static const uint64_t static_value2 = 0x948e7b712dd4d7c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab03_example_srv/point_rotResponse";
  }

  static const char* value(const ::lab03_example_srv::point_rotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point out_p\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::lab03_example_srv::point_rotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.out_p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct point_rotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab03_example_srv::point_rotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab03_example_srv::point_rotResponse_<ContainerAllocator>& v)
  {
    s << indent << "out_p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.out_p);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB03_EXAMPLE_SRV_MESSAGE_POINT_ROTRESPONSE_H
