// Generated by gencpp from file lab03_example_srv/point_rot.msg
// DO NOT EDIT!


#ifndef LAB03_EXAMPLE_SRV_MESSAGE_POINT_ROT_H
#define LAB03_EXAMPLE_SRV_MESSAGE_POINT_ROT_H

#include <ros/service_traits.h>


#include <lab03_example_srv/point_rotRequest.h>
#include <lab03_example_srv/point_rotResponse.h>


namespace lab03_example_srv
{

struct point_rot
{

typedef point_rotRequest Request;
typedef point_rotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct point_rot
} // namespace lab03_example_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab03_example_srv::point_rot > {
  static const char* value()
  {
    return "ba189fd216bf80200d5f8fd950cfe767";
  }

  static const char* value(const ::lab03_example_srv::point_rot&) { return value(); }
};

template<>
struct DataType< ::lab03_example_srv::point_rot > {
  static const char* value()
  {
    return "lab03_example_srv/point_rot";
  }

  static const char* value(const ::lab03_example_srv::point_rot&) { return value(); }
};


// service_traits::MD5Sum< ::lab03_example_srv::point_rotRequest> should match
// service_traits::MD5Sum< ::lab03_example_srv::point_rot >
template<>
struct MD5Sum< ::lab03_example_srv::point_rotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab03_example_srv::point_rot >::value();
  }
  static const char* value(const ::lab03_example_srv::point_rotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab03_example_srv::point_rotRequest> should match
// service_traits::DataType< ::lab03_example_srv::point_rot >
template<>
struct DataType< ::lab03_example_srv::point_rotRequest>
{
  static const char* value()
  {
    return DataType< ::lab03_example_srv::point_rot >::value();
  }
  static const char* value(const ::lab03_example_srv::point_rotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab03_example_srv::point_rotResponse> should match
// service_traits::MD5Sum< ::lab03_example_srv::point_rot >
template<>
struct MD5Sum< ::lab03_example_srv::point_rotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab03_example_srv::point_rot >::value();
  }
  static const char* value(const ::lab03_example_srv::point_rotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab03_example_srv::point_rotResponse> should match
// service_traits::DataType< ::lab03_example_srv::point_rot >
template<>
struct DataType< ::lab03_example_srv::point_rotResponse>
{
  static const char* value()
  {
    return DataType< ::lab03_example_srv::point_rot >::value();
  }
  static const char* value(const ::lab03_example_srv::point_rotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB03_EXAMPLE_SRV_MESSAGE_POINT_ROT_H
