// Generated by gencpp from file lab03_task/rotmat2quat.msg
// DO NOT EDIT!


#ifndef LAB03_TASK_MESSAGE_ROTMAT2QUAT_H
#define LAB03_TASK_MESSAGE_ROTMAT2QUAT_H

#include <ros/service_traits.h>


#include <lab03_task/rotmat2quatRequest.h>
#include <lab03_task/rotmat2quatResponse.h>


namespace lab03_task
{

struct rotmat2quat
{

typedef rotmat2quatRequest Request;
typedef rotmat2quatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rotmat2quat
} // namespace lab03_task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab03_task::rotmat2quat > {
  static const char* value()
  {
    return "ba65a11ccca794afa870de4e5dad99f0";
  }

  static const char* value(const ::lab03_task::rotmat2quat&) { return value(); }
};

template<>
struct DataType< ::lab03_task::rotmat2quat > {
  static const char* value()
  {
    return "lab03_task/rotmat2quat";
  }

  static const char* value(const ::lab03_task::rotmat2quat&) { return value(); }
};


// service_traits::MD5Sum< ::lab03_task::rotmat2quatRequest> should match
// service_traits::MD5Sum< ::lab03_task::rotmat2quat >
template<>
struct MD5Sum< ::lab03_task::rotmat2quatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab03_task::rotmat2quat >::value();
  }
  static const char* value(const ::lab03_task::rotmat2quatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab03_task::rotmat2quatRequest> should match
// service_traits::DataType< ::lab03_task::rotmat2quat >
template<>
struct DataType< ::lab03_task::rotmat2quatRequest>
{
  static const char* value()
  {
    return DataType< ::lab03_task::rotmat2quat >::value();
  }
  static const char* value(const ::lab03_task::rotmat2quatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab03_task::rotmat2quatResponse> should match
// service_traits::MD5Sum< ::lab03_task::rotmat2quat >
template<>
struct MD5Sum< ::lab03_task::rotmat2quatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab03_task::rotmat2quat >::value();
  }
  static const char* value(const ::lab03_task::rotmat2quatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab03_task::rotmat2quatResponse> should match
// service_traits::DataType< ::lab03_task::rotmat2quat >
template<>
struct DataType< ::lab03_task::rotmat2quatResponse>
{
  static const char* value()
  {
    return DataType< ::lab03_task::rotmat2quat >::value();
  }
  static const char* value(const ::lab03_task::rotmat2quatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB03_TASK_MESSAGE_ROTMAT2QUAT_H
