(cl:defpackage cw1q4_srv-srv
  (:use )
  (:export
   "QUAT2RODRIGUES"
   "<QUAT2RODRIGUES-REQUEST>"
   "QUAT2RODRIGUES-REQUEST"
   "<QUAT2RODRIGUES-RESPONSE>"
   "QUAT2RODRIGUES-RESPONSE"
   "QUAT2ZYX"
   "<QUAT2ZYX-REQUEST>"
   "QUAT2ZYX-REQUEST"
   "<QUAT2ZYX-RESPONSE>"
   "QUAT2ZYX-RESPONSE"
  ))

