// Generated by gencpp from file cw1q4_srv/quat2rodrigues.msg
// DO NOT EDIT!


#ifndef CW1Q4_SRV_MESSAGE_QUAT2RODRIGUES_H
#define CW1Q4_SRV_MESSAGE_QUAT2RODRIGUES_H

#include <ros/service_traits.h>


#include <cw1q4_srv/quat2rodriguesRequest.h>
#include <cw1q4_srv/quat2rodriguesResponse.h>


namespace cw1q4_srv
{

struct quat2rodrigues
{

typedef quat2rodriguesRequest Request;
typedef quat2rodriguesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct quat2rodrigues
} // namespace cw1q4_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw1q4_srv::quat2rodrigues > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cw1q4_srv::quat2rodrigues&) { return value(); }
};

template<>
struct DataType< ::cw1q4_srv::quat2rodrigues > {
  static const char* value()
  {
    return "cw1q4_srv/quat2rodrigues";
  }

  static const char* value(const ::cw1q4_srv::quat2rodrigues&) { return value(); }
};


// service_traits::MD5Sum< ::cw1q4_srv::quat2rodriguesRequest> should match
// service_traits::MD5Sum< ::cw1q4_srv::quat2rodrigues >
template<>
struct MD5Sum< ::cw1q4_srv::quat2rodriguesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw1q4_srv::quat2rodrigues >::value();
  }
  static const char* value(const ::cw1q4_srv::quat2rodriguesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1q4_srv::quat2rodriguesRequest> should match
// service_traits::DataType< ::cw1q4_srv::quat2rodrigues >
template<>
struct DataType< ::cw1q4_srv::quat2rodriguesRequest>
{
  static const char* value()
  {
    return DataType< ::cw1q4_srv::quat2rodrigues >::value();
  }
  static const char* value(const ::cw1q4_srv::quat2rodriguesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw1q4_srv::quat2rodriguesResponse> should match
// service_traits::MD5Sum< ::cw1q4_srv::quat2rodrigues >
template<>
struct MD5Sum< ::cw1q4_srv::quat2rodriguesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw1q4_srv::quat2rodrigues >::value();
  }
  static const char* value(const ::cw1q4_srv::quat2rodriguesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1q4_srv::quat2rodriguesResponse> should match
// service_traits::DataType< ::cw1q4_srv::quat2rodrigues >
template<>
struct DataType< ::cw1q4_srv::quat2rodriguesResponse>
{
  static const char* value()
  {
    return DataType< ::cw1q4_srv::quat2rodrigues >::value();
  }
  static const char* value(const ::cw1q4_srv::quat2rodriguesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW1Q4_SRV_MESSAGE_QUAT2RODRIGUES_H
